image: fedora:latest

stages:
  - build

before_script:
  - dnf install -y glib2-devel gstreamer1-devel
                   meson vte291-devel which

build_gnome_mud:
  stage: build
  script:
    - meson _build -Dgstreamer=enabled -Dmccp=enabled -Ddebug-logger=true
    - ninja -C _build install
